### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by asif-saad**
hello, 
i have faced some data timestamp which is unsorted (at the top for example: 2022 speech among 2023 speeches), also is it possible to sort them in descending order, additionally, please put the data time format on the header index of the column, as many of us are accustomed to DD/MM/YY Thank you.

### CODE REVIEW

**Comment by asif-saad** [comment]
cheers

**Comment by natestemen** [comment]
Thanks Asif for bringing this up! I've fixed the dates on the first two lines, they were meant to be 2023, so everything should be sorted in descending order. Also good point for the date format. I think it would actually be great to have the dates in an [ISO standard format](https://www.iso.org/iso-8601-date-and-time-format.html). Is that something you'd be willing to do? In the meantime I've added the currently used format to the column title to alleviate some and disambiguation.

**Comment by asif-saad** [comment]
yes, you can follow the ISO standard format, and would be even better mentioning the date time format on the column's header.

**Comment by natestemen** [comment]
Is that something you'd be interested in doing?

**Comment by asif-saad** [comment]
i am sorry, but what are you referring to by saying "i am being interested doing"?

**Comment by natestemen** [comment]
I mean are you interested in converting the date column to a date format that conforms with the ISO standard.

**Comment by asif-saad** [comment]
okay, i can try!

**Comment by asif-saad** [comment]
let me know if you want me to convert.

**Comment by natestemen** [comment]
Sounds good! Let me know if you have any questions!

**Pull request closed without merging**
