### PR TITLE
Merge pull request #1 from unitaryfund/main

### PR DESCRIPTION
**Pull request by asif-saad**
The date time format has been updated as per ISO format (https://www.iso.org/iso-8601-date-and-time-format.html).

### CODE REVIEW

**Comment by natestemen** [comment]
Hey Asif, thanks for starting this! Currently it looks like there are no [changes](https://github.com/unitaryfund/quantum-wednesday/pull/10/files) made to the code, however. Are you sure you included them?

**Comment by asif-saad** [comment]
could you check now?
is it okay?

**Review by natestemen — CHANGES_REQUESTED** [review]
Awesome, thanks a bunch Asif. Looks like one line got missed, but good otherwise.

As a tip when contributing to projects, remember to use both informative titles for PRs and git commit messages that describe the changes that were made.

**Review by natestemen — APPROVED** [review]
Nice work Asif! Thanks for doing this!

**Pull request merged**
